### ISSUE TITLE
Position erste LED

### ISSUE THREAD

**Issue by Hive89** [N1cls/Wordclock#11]
Hallo, zunächst möchte ich mich für deine tolle Arbeit bedanken.

Gibt es eine Möglichkeit die erste LED Oben Links statt Oben Rechts zu definieren? Vielen Dank!

**Comment by AWSW-de** [comment]
Hi,
Danke Dir! Schau Dir mal diese Funktion an:

„void showMinutes(int minutes)“

In der wird die Reihenfolge der äußeren LEDs festgelegt. 

PS: Heute ist ein neues Modell erschienen: https://www.printables.com/de/model/749967-wordclock-16x8-2024

Viele Grüße =)

**Comment by Hive89** [comment]
Vielen Dank für die Schnelle Antwort. Ich habe mittlerweile deinen Code geforked und leicht abgeändert und eine Option erstellt mit der man auch die erste LED im strip in eine der Ecken setzen kann. Ist noch nicht perfekt, da ich nur die beiden Oben Rechts oder Oben Links testen konnte.

**Comment by AWSW-de** [comment]
Gerne. Viel Spaß damit =)
