### ISSUE TITLE
Regenbogen farben

### ISSUE THREAD

**Issue by M3XXstmk** [N1cls/Wordclock#2]
Hallo :) ich hoffe ich mache es so richtig mit meiner Anfrage... Also erstens ich liebe diese wordclock! Ich finde es so genial das sich jemand die Arbeit macht und sich die Zeit nimmt um ein Programm für dieses Projekt zu schreiben - danke. Ich würde gerne über Paypal etwas dafür spenden aber ich habe bis jetzt keine Möglichkeit gefunden - vielleicht kann mir jemand sagen wie ich das machen kann.

Meine eigentliche Frage ist ob es möglich ist wieder die Regenbogen Funktion zu aktivieren - also so der Regenbogen das nicht alle Buchstaben die selbe Farbe haben sonder so wie früher wo wirklich ein Regenbogen von oben bis unten sichtbar war.

Liebe Grüße aus Österreich,
Markus

**Comment by AWSW-de** [comment]
Hallo,
erst mal vielen Dank für die netten Worte und gern geschehen. Über mein [Printables Profil](https://www.printables.com/model/262523-deichkind-music-reactive-led-helmet) findest Du einen entsprechenden Link. Danke dafür vorab.

Wenn ich Deine Anfrage richtig verstehe, würdest Du gern wieder die vorherige Regenbogen Funktion aktivieren können. Das könnte ich in den Einstellungen umschaltbar gestalten. Dann könnte man entweder die vorherige oder die aktuelle Regenbogen Farb-Funktion aktivieren…

**Comment by M3XXstmk** [comment]
Genau so meine ich es - der Buchstaben Regenbogen wie früher. Es wäre wirklich schön wenn du dir dafür die Zeit nehmen könntest. Danke nochmal - wie gesagt ich habe wirklich eine große Freude das du dieses Projekt öffentlich gemacht hast.

**Comment by AWSW-de** [comment]
Hallo, 
Version 4.9 sollte diese Funktion nun wieder bieten. 
VIelen Dank Dir noch mal und weiterhin viel Spaß mit der WortUhr :)

**Comment by M3XXstmk** [comment]
Wow vielen lieben dank! Du machst mir damit eine große Freude! 
![IMG_20220905_004751_571](https://user-images.githubusercontent.com/93610282/189497265-c32b68e8-96b5-4478-b719-3b681e9ccbab.jpg)

**Comment by AWSW-de** [comment]
Sehr gern. Die sehen toll aus! Viele Grüße
