### ISSUE TITLE
Question: version without RTC ?

### ISSUE THREAD

**Issue by schroepfer** [N1cls/Wordclock#3]
Hello,
thanks for your fantastic work!
I don't have an RTC an I think there is no need, if you have WiFi and a timeserver.

Do you have a version without the need of a RTC?
Regards
Jürgen

**Comment by AWSW-de** [comment]
Hello Jürgen,
thanks a lot for your nice words. :)

Yes, that should be possible as an option in this project. I will have a look at this in the next days/weeks. I am currently working on the new update variant, shown on the start page here in the planned functions, that will let you update to a new version with 1 click… 

Kind regards 
Axel

**Comment by schroepfer** [comment]
Thanks a lot! That would be fine!

**Comment by AWSW-de** [comment]
Hello,
version 5.2 with the new update function is now available. Next up is your request for the RTC... :)
 
NOTE: After the update to 5.2 it will always show an available update to 5.2.1, which is 5.2 again. This is just for tests to be able to use the update function not just once. In newer versions (>=5.3) it will show that the updated version is the available version...

Kind regards
Axel

**Comment by AWSW-de** [comment]
Hi Jürgen,
version 5.3 with the optional removal of the need of an RTC board is available.
No configuration should be needed. 
If there is no RTC detected a note is shown in the serial monitor until the configuration page is saved once. 
Tested with and without an RTC on a WordClock.

Please let me know if it works for you now.

Kind regards,
Axel

**Comment by schroepfer** [comment]
Thanks, it works fine, but:
the clock is mirrored, because my WS28B12 begins on the other side, than yours.
I couldn't find a setting to fix this.

Regards
Jürgen

**Comment by AWSW-de** [comment]
Thanks for the feedback. 

I guess you mean the minutes LEDs in the corners… Please check the setting “ Minuten LEDs Ecken Reihenfolge im Uhrzeigersinn?’

Kind regards

**Comment by schroepfer** [comment]
Nein, die komplette Uhr ist gespiegelt.
Meine WS-LED's beginnen oben links bei dem E von "ES IST..."
In deinem Code und deiner Uhr wahrscheinlich oben rechts.

**Comment by AWSW-de** [comment]
OK, das kann man nicht so einfach spiegeln. 
Laut der Anleitung von N1cls bitte beim F beginnen, also oben rechts. 
Bitte entsprechend die Verkabelung anpassen.
Viel Erfolg
