### ISSUE TITLE
If RTC is not connected not incrementing time

### ISSUE THREAD

**Issue by jvdkieft** [N1cls/Wordclock#4]
I think if there is not RTC, the time that is used to drive the LEDs is only updated hourly. In handleTime, where the iHour, iMinute, etc. are set, they are only being set hourly since rtcReadTime is not being called. I removed the if (i != lastRequest) check and it seems to be working without an RTC. I think that also the NTP time is being set once on Wifi initialize and never again.

**Comment by N1cls** [comment]
Hey, that is how it is suppose to work to minimize the effort for the micro controller.

**Comment by jvdkieft** [comment]
So without the RTC it only updates the display every hour. Okay.

**Comment by jvdkieft** [comment]
Maybe I misunderstand - are you saying it only gets the NTP time on startup to minimize effort, or only updates the time shown on the display once an hour to minimize effort? HandleTime only updates the display once an hour with the if on line 1999. With that there and no RTC the displayed time only is updated once an hour. With it removed, the NTP call still isn't made, but the time does get updated as it should. It shouldn't be an additional effor to do that.

**Comment by AWSW-de** [comment]
Hello ivdkieft,
I just had a look at my 2nd WordClock which runs now without an RTC board and as far as I could see now, I would say you are right that there is then a new bug in the code through the changes I made for version 5.3. I must have overlooked this during the tests then. I will have a closer look at this in the next days and thanks also for the hint to the fix you already found for your device.
Thanks and kind regards

**Comment by AWSW-de** [comment]
Hello,
version 5.4 should fix this issue.
Kind regards

**Comment by AWSW-de** [comment]
Hello,
version 5.4 should fix this issue.
Kind regards
