### ISSUE TITLE
Access to the watch's website/settings no longer works

### ISSUE THREAD

**Issue by Julian9102** [N1cls/Wordclock#6]
Hello, the following day after updating the software to v5.7, access to the watch's website/settings no longer works. However, the clock shows as connected and reachable in my router. Same with my second watch. Access was still possible immediately after the software update.

**Comment by AWSW-de** [comment]
Hello,
here is a bug in the WiFi Manager (i think) which can cause this behaviour. Have you tried a power cycle and if you use 2 clock have they different hostnames set in the config? Otherwise the same name will block the access.
How do you try to enter the WordClock(s)? Via http://IP-address or http://hostname ?

Hope this helps

**Comment by Julian9102** [comment]
First i tried some power-on-cycle without success and both Wordclocks are named different (#1 and #2). I tried with the IP-Adress.
What else can i try? Is there an update without this wifi error?
The colored display is great so i actually don't want to go back to v1...

**Comment by AWSW-de** [comment]
I am running several of these WordClocks with V5.7 here. And I know from several users that it works in general. So it should be something in your setup - is my guess! This may sound harsh but some errors need to be hunted down like that… Please try to follow the actions closely to find a fast solution. If you have questions please ask… Thanks! 😊 

**Questions:**
- Which ESP8266 are you using in the devices?
- Do you use the unchanged code or did you modify it?
- Do you use the default led setup of the project?
- Does your WiFi turn off e.g. over night?
- Is the WiFi SSID visible or hidden?
- Do you use the RTC board?
- Can you “ping” the in your router listed ip-addresses of the WordClocks?
- How “good” is your WiFi signal strength where the clocks are located?


**We need do break this down step by step to find a solution for you:**
1. Disconnect both devices from power for at least 15 minutes. 
2. Use (at first) in the next steps 1 WordClock only!
3. Connect one of the ESP8266 to Arduino IDE
4. Set the transfer rate in Arduino IDE to 115200, not higher
5. Erase the complete flash of both ESP8266 with the Arduino IDE. In the transfer options you will find the option to delete the complete flash of the ESP8266 when you flash the chip again with Arduino again.
6. Setup WiFi again for this 1 WordClock. If it does not require to do so the erase of the ESP was not done before…
7. Check that it logs on to your WiFi.
8. Unplug the device 1x from power to fix a bug in the WiFi manager function.
9. Plug in the clock again and check the complete startup including that it shows the time.
10. Check the web access 
11. Configure the host name ID for this device. 
12. Leave it running and check each hour (if possible) for about 24 hours if is still possible to reach.
13. If it works after 24 hours repeat the steps for the 2nd WordClock. Until then please leave it off!


Hope this helps!

**Comment by AWSW-de** [comment]
Closed because of no response.

**Comment by AWSW-de** [comment]
Please update to V5.9. Possible bug fix included. HTH!
