### ISSUE TITLE
Umstellen auf Anzeige DREIVIERTEL / VIERTEL

### ISSUE THREAD

**Issue by Helmut2006** [N1cls/Wordclock#7]
Hallo,
gibt es eine Möglichkeit die Anzeige DREIVIERTEL zu aktivieren? Also z.B. aus ES IST VIERTEL VOR DREI mach ES IST DREIVIERTEL DREI? 

Viele Grüße aus Jessen

Christian

**Comment by AWSW-de** [comment]
Hallo,
bitte auf V5.8. aktualisieren und in der settings.h den Switch in "DEspecial1" von "VIERTEL VOR" = "0" auf "DREIVIERTEL" = "1" setzen. Dann sollte sich die Änderung bei den x:45 Zeiten ergeben. Nur ganz grob getestet, aber sollte klappen.

HTH und viele Grüße
AWSW

**Comment by Helmut2006** [comment]
Hallo,Das ging ja schnell. Probiere ich gleich aus. Vielen Dank und einen schönen Sonntag noch.Viele Grüße Christian Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AWSW-de ***@***.***> Datum: 29.01.23  15:52  (GMT+01:00) An: N1cls/Wordclock ***@***.***> Cc: Helmut2006 ***@***.***>, Author ***@***.***> Betreff: Re: [N1cls/Wordclock] umstellen auf Anzeige DREIVIERTEL (Issue #7) 

Hallo,

bitte auf V5.8. aktualisieren und in der settings.h den Switch in "DEspecial1" von "VIERTEL VOR" = "0" auf "DREIVIERTEL" = "1" setzen. Dann sollte sich die Änderung bei den x:45 Zeiten ergeben. Nur ganz grob getestet, aber sollte klappen.

HTH und viele Grüße

AWSW

**Comment by AWSW-de** [comment]
Hi,
gern geschehen. Lass mich bitte wissen, ob es so OK ist. Waren an sich nur 5 Zeilen zu ändern/ergänzen.. Dann kann ich das Ticket hier schließen. 

Danke und schönen Abend noch.

Viele Grüße

**Comment by Helmut2006** [comment]
Hallo,Habe das Update gemacht. Jetzt muss ich noch eine dumme Frage stellen. Wie komme ich in die setting.h? Auf der Weboberfläche kann ich leider nichts finden.  Danke Gruß Christian Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AWSW-de ***@***.***> Datum: 29.01.23  17:47  (GMT+01:00) An: N1cls/Wordclock ***@***.***> Cc: Helmut2006 ***@***.***>, Author ***@***.***> Betreff: Re: [N1cls/Wordclock] umstellen auf Anzeige DREIVIERTEL (Issue #7) 

Hi,

gern geschehen. Lass mich bitte wissen, ob es so OK ist. Waren an sich nur 5 Zeilen zu ändern/ergänzen.. Dann kann ich das Ticket hier schließen.

Danke und schönen Abend noch.

Viele Grüße

**Comment by AWSW-de** [comment]
Kein Problem. Habe das (erst mal) nicht in die Weboberfläche integriert, damit du erst mal testen kannst… Um ehrlich zu sein, diese Dreiviertel Schreibweise hab ich noch nie verstanden... 🙈😋

In der Arduino IDE hast du ja den Code… In einem Tab in Arduino wirst du die “Settings.h“ Datei sehen. Dort suchst du nach dem o.g. neuen Schalter und machst aus der 0 eine 1 und lädst den Code auf die Uhr… Danach ist es aktiv.

**Comment by Helmut2006** [comment]
Okay, habe das Update online eingespielt. Dann muss ich die Uhr nochmal auseinander bauen um an den USB Anschluss zu kommen. Mache ich bei Gelegenheit. Nach dem Update hat die Uhr eine neue IP erhalten. Das hatte ich sonst nach einem Update nicht. Und die Funktion PING Monitor scheint jetzt gestört zu sein. Uhr geht jetzt aus obwohl unsere Handys im WLan sind. Ich gebe die nachher nochmal neu ein obwohl die IPs auf der Weboberfläche noch stimmen. Gruß Christian Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AWSW-de ***@***.***> Datum: 29.01.23  17:56  (GMT+01:00) An: N1cls/Wordclock ***@***.***> Cc: Helmut2006 ***@***.***>, Author ***@***.***> Betreff: Re: [N1cls/Wordclock] umstellen auf Anzeige DREIVIERTEL (Issue #7) 

Kein Problem. Habe das (erst mal) nicht in die Weboberfläche integriert, damit du erst mal testen kannst… Um ehrlich zu sein, diese Dreiviertel Schreibweise hab ich noch nie verstanden... 🙈😋

In der Arduino IDE hast du ja den Code… In einem Tab in Arduino wirst du die “Settings.h“ Datei sehen. Dort suchst du nach dem o.g. neuen Schalter und machst aus der 0 eine 1 und lädst den Code auf die Uhr… Danach ist es aktiv.

**Comment by Helmut2006** [comment]
Hier mal ein Bild von de Schmuckstück. Ist ca. 450 x 450mm.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AWSW-de ***@***.***> Datum: 29.01.23  17:56  (GMT+01:00) An: N1cls/Wordclock ***@***.***> Cc: Helmut2006 ***@***.***>, Author ***@***.***> Betreff: Re: [N1cls/Wordclock] umstellen auf Anzeige DREIVIERTEL (Issue #7) 

Kein Problem. Habe das (erst mal) nicht in die Weboberfläche integriert, damit du erst mal testen kannst… Um ehrlich zu sein, diese Dreiviertel Schreibweise hab ich noch nie verstanden... 🙈😋

In der Arduino IDE hast du ja den Code… In einem Tab in Arduino wirst du die “Settings.h“ Datei sehen. Dort suchst du nach dem o.g. neuen Schalter und machst aus der 0 eine 1 und lädst den Code auf die Uhr… Danach ist es aktiv.

**Comment by AWSW-de** [comment]
Hi,
ok, wenn du die Uhr erst zerlegen musst, schreib ich Dir lieber einen Schalter in die WebOberfläche... Dachte Du könntest das schnell so hoch laden... Muss eh einen kleinen Bug fixen... Gib mir was Zeit bitte... Muss mich erst mal wieder da rein denken...

Das Bild kam leider nicht an.

**Comment by Helmut2006** [comment]
Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AWSW-de ***@***.***> Datum: 29.01.23  18:29  (GMT+01:00) An: N1cls/Wordclock ***@***.***> Cc: Helmut2006 ***@***.***>, Author ***@***.***> Betreff: Re: [N1cls/Wordclock] umstellen auf Anzeige DREIVIERTEL (Issue #7) 

Hi,

ok, wenn du die Uhr erst zerlegen musst, schreib ich Dir lieber einen Schalter in die WebOberfläche... Dachte Du könntest das schnell so hoch laden... Muss eh einen kleinen Bug fixen... Gib mir was Zeit bitte... Muss mich erst mal wieder da rein denken...

Das Bild kam leider nicht an.

**Comment by AWSW-de** [comment]
Bitte auf V5.9 aktualisieren... Dann kann die Uhr an der Wand bleiben. Einstellung nun in der Weboberfläche in deutscher Spracheinstellung verfügbar... Viel Spaß damit!

**Comment by Helmut2006** [comment]
Hallo,DREIVIERTEL Anzeige funktioniert. Toll gemacht, Dankeschön. Der Pingmonitor scheint immer noch ein Problem zu haben. Das ist aber kein Problem. Soviel Strom braucht das ganze auch nicht;-). Schönen Sonntag Abend Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: AWSW-de ***@***.***> Datum: 29.01.23  19:07  (GMT+01:00) An: N1cls/Wordclock ***@***.***> Cc: Helmut2006 ***@***.***>, Author ***@***.***> Betreff: Re: [N1cls/Wordclock] umstellen auf Anzeige DREIVIERTEL (Issue #7) 

Bitte auf V5.9 aktualisieren... Dann kann die Uhr an der Wand bleiben. Einstellung nun in der Weboberfläche in deutscher Spracheinstellung verfügbar... Viel Spaß damit!

**Comment by AWSW-de** [comment]
Sehr gerne. Prüfe bitte noch mal die Einstellung des PING Monitors. Hatte ich eben erfolgreich nutzen können…

Danke auch und schönen Abend noch.

**Comment by Helmut2006** [comment]
Hallo,

 

und einen schönen Sonntag. Einen kleine Idee hätte ich noch für den „dreiviertel“ Modus. Die Anzeige „viertel nach“ könnte man noch in „viertel“ ändern.

 

Ich wünsche noch einen schönen Abend und eine angenehme Woche.

 

Viele Grüße

 

Christian

 

Von: AWSW-de ***@***.***> 
Gesendet: Sonntag, 29. Januar 2023 19:55
An: N1cls/Wordclock ***@***.***>
Cc: Helmut2006 ***@***.***>; Author ***@***.***>
Betreff: Re: [N1cls/Wordclock] umstellen auf Anzeige DREIVIERTEL (Issue #7)

 

Sehr gerne. Prüfe bitte noch mal die Einstellung des PING Monitors. Hatte ich eben erfolgreich nutzen können…

Danke auch und schönen Abend noch.

**Comment by AWSW-de** [comment]
Hi,
schau ich mir die Tage an. 
viele Grüße

**Comment by AWSW-de** [comment]
Hi,
die Änderung ist in Version V5.9.1 enthalten. Bitte entsprechend aktualisieren.
VIele Grüße

**Comment by Helmut2006** [comment]
Hallo,

 

vielen Dank für die schnelle Antwort. Es gibt da noch einen Bug mit der Stunde. Es heißt ja auf der einen Seite VIERTEL NACH SIEBEN und auf der anderen Seite muss es dann VIERTEL ACHT heißen.

 

Viele Grüße

 

Christian

 

Von: AWSW-de ***@***.***> 
Gesendet: Dienstag, 14. Februar 2023 18:08
An: N1cls/Wordclock ***@***.***>
Cc: Helmut2006 ***@***.***>; Author ***@***.***>
Betreff: Re: [N1cls/Wordclock] Umstellen auf Anzeige DREIVIERTEL / VIERTEL (Issue #7)

 

Hi,
die Änderung ist in Version V5.9.1 enthalten. Bitte entsprechend aktualisieren.
VIele Grüße

**Comment by AWSW-de** [comment]
Hi,
danke für den Hinweis… Entschuldige, aber diese Zähl-/Sprechweise werde ich wohl leider nie richtig verstehen. 🙈😂🙈
Schau ich mir zeitnah an.
Viele Grüße

**Comment by AWSW-de** [comment]
Hi,

probier das mal bitte mit V5.9.2... Wie gesagt ich verstehe diese Schreibweise leider immer noch nicht wirklich.

Sollte sich noch ein Fehler darin befinden, dann bitte mal diese Liste mit den kompletten Texten füllen:
####################################
09:00 = Es ist 
09:05 = Es ist 
09:10 = Es ist 
09:15 = Es ist 
09:20 = Es ist 
09:25 = Es ist 
09:30 = Es ist 
09:35 = Es ist 
09:40 = Es ist 
09:45 = Es ist 
09:50 = Es ist 
09:55 = Es ist 
####################################

Viele Grüße
