### ISSUE TITLE
Datumsanzeige als Lauftext

### ISSUE THREAD

**Issue by M3XXstmk** [N1cls/Wordclock#8]
Hallo ich hab mal wieder eine Frage: 
Ist es möglich die Datumsanzeige auch alle X Minuten oder zur vollen Stunde drüber laufen zu lassen oder ist es nur alle 30 Sekunden möglich. 
Ich finde alle 30 Sekunden ist ziemlich oft. 

Liebe Grüße aus Graz,
Markus

**Comment by AWSW-de** [comment]
Hi Markus,
ja, klar, das ist möglich. Deshalb habe ich die Anzeige an sich auch oft inaktiv…

Wie oft genau meinst Du wäre es sinnvoll die Ausgabe zu starten? 

Viele Grüße 🖖

**Comment by AWSW-de** [comment]
Alternativ würde ich mittlerweile eine solche Darstellung bevorzugen, so wie ich sie für die IP-Adresse hier auch verwende:
https://youtu.be/5VF4V6CXWMs

![6AADCAE1-5194-42CB-9752-489232C7B0D3](https://user-images.githubusercontent.com/34800740/221657275-9aa04b4f-4349-461c-8377-e9d740647c80.jpeg)
![8179208E-1A87-4C54-BC42-9F446AF472E6](https://user-images.githubusercontent.com/34800740/221657281-6b40cb2f-3b78-4b01-acce-151babc56921.jpeg)

**Comment by M3XXstmk** [comment]
Ich finde es reicht aus wenn das Datum alle 15/30 Minuten über die Anzeige läuft. Das Datum kann mit oder ohne der Jahreszahl sein. Auch könnte die Uhrzeit mit als Lauftext darüber laufen - das würde man dann gut lesen können wenn die Uhr weiter entfernt steht.

**Comment by AWSW-de** [comment]
Hi, 
gute Idee. Ich lasse mir dazu mal Etwas einfallen.
Ich poste hier wieder sobald es dazu etwas Neues gibt. 
Viele Grüße 🖖

**Comment by M3XXstmk** [comment]
hallo :) gibts schon was neues?

**Comment by AWSW-de** [comment]
Hi 🖖
Noch nicht. Bin gerade hier dran: https://www.printables.com/de/model/331012-wordclock-16x16-led-matrix 
Die User warten schon etwas länger. Danach schau ich mir das hier an. 😊

**Comment by AWSW-de** [comment]
Hi, Version V5.9.3 sollte die Änderung auf eine Anzeige alle 30 Minuten ermöglichen. Die Jahreszahl habe ich aber drin gelassen.
Viel Spaß damit!
Viele Grüße
