### ISSUE TITLE
When ping is used, brightness doesn't go to night-mode directly

### ISSUE THREAD

**Issue by AstroxV** [N1cls/Wordclock#9]
When the PING function is used, the display blinks after every ping request to its day-brightness while it should be in night-mode.

I have my display set to use night mode and each time a ping-check is done (every 30 seconds) the display goes to its normal brightines after it goes dim again.

**Comment by AWSW-de** [comment]
Hi!
Interesting that I never saw this myself, but I can confirm this behaviour. 
Thanks for the hint. I will have a look at this.

**Comment by AWSW-de** [comment]
Hi,
version V5.9.4  should fix this issue.
Kind regards :)
